# Generated by Django 2.2.13 on 2022-06-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220611_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Regular account', null=True),
        ),
    ]
