# Generated by Django 2.2.13 on 2022-06-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220612_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('username', models.CharField(blank=True, max_length=40, null=True)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('rank', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=15, null=True)),
                ('qty', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
